export interface SeedCustomer {
    id: string;
    name: string;
    email: string;
}

export interface SeedProduct {
    id: string;
    name: string;
}

export interface SeedInventoryItem {
    productId: string;
    quantity: number;
}


export const SEED_CUSTOMERS: SeedCustomer[] = [
    { id: "ABC", name: "John Doe", email: "john.doe@gmail.com" },
    { id: "DEF", name: "Jane Doe", email: "jane.doe@outlook.com" },
    { id: "CUST003", name: "Michael Chen", email: "michael.chen@yahoo.com" },
    { id: "CUST004", name: "Sarah Johnson", email: "sarah.johnson@icloud.com" },
    { id: "CUST005", name: "David Martinez", email: "david.martinez@proton.me" },
    { id: "CUST006", name: "Emily Brown", email: "emily.brown@gmail.com" },
    { id: "CUST007", name: "James Wilson", email: "james.wilson@hotmail.com" },
    { id: "CUST008", name: "Olivia Taylor", email: "olivia.taylor@outlook.com" },
    { id: "CUST009", name: "Daniel Anderson", email: "daniel.anderson@gmail.com" },
    { id: "CUST010", name: "Sophia Thomas", email: "sophia.thomas@yahoo.com" },
    { id: "CUST011", name: "William Jackson", email: "william.jackson@icloud.com" },
    { id: "CUST012", name: "Ava White", email: "ava.white@gmail.com" },
    { id: "CUST013", name: "Benjamin Harris", email: "benjamin.harris@outlook.com" },
    { id: "CUST014", name: "Mia Martin", email: "mia.martin@proton.me" },
    { id: "CUST015", name: "Lucas Thompson", email: "lucas.thompson@gmail.com" },
    { id: "CUST016", name: "Charlotte Garcia", email: "charlotte.garcia@yahoo.com" },
    { id: "CUST017", name: "Henry Robinson", email: "henry.robinson@hotmail.com" },
    { id: "CUST018", name: "Amelia Clark", email: "amelia.clark@icloud.com" },
    { id: "CUST019", name: "Alexander Lewis", email: "alexander.lewis@gmail.com" },
    { id: "CUST020", name: "Harper Lee", email: "harper.lee@outlook.com" },
    { id: "CUST021", name: "Sebastian Walker", email: "sebastian.walker@gmail.com" },
    { id: "CUST022", name: "Evelyn Hall", email: "evelyn.hall@yahoo.com" },
    { id: "CUST023", name: "Jack Allen", email: "jack.allen@proton.me" },
    { id: "CUST024", name: "Abigail Young", email: "abigail.young@icloud.com" },
    { id: "CUST025", name: "Owen King", email: "owen.king@gmail.com" },
    { id: "CUST026", name: "Ella Wright", email: "ella.wright@hotmail.com" },
    { id: "CUST027", name: "Samuel Scott", email: "samuel.scott@outlook.com" },
    { id: "CUST028", name: "Scarlett Green", email: "scarlett.green@gmail.com" },
    { id: "CUST029", name: "Matthew Baker", email: "matthew.baker@yahoo.com" },
    { id: "CUST030", name: "Grace Adams", email: "grace.adams@icloud.com" },
    { id: "CUST031", name: "Joseph Nelson", email: "joseph.nelson@proton.me" },
    { id: "CUST032", name: "Chloe Hill", email: "chloe.hill@gmail.com" },
    { id: "CUST033", name: "Ethan Perez", email: "ethan.perez@outlook.com" },
    { id: "CUST034", name: "Victoria Ramirez", email: "victoria.ramirez@yahoo.com" },
    { id: "CUST035", name: "Andrew Campbell", email: "andrew.campbell@hotmail.com" },
    { id: "CUST036", name: "Lily Mitchell", email: "lily.mitchell@gmail.com" },
    { id: "CUST037", name: "Ryan Roberts", email: "ryan.roberts@icloud.com" },
    { id: "CUST038", name: "Zoey Carter", email: "zoey.carter@outlook.com" },
    { id: "CUST039", name: "Nathan Phillips", email: "nathan.phillips@proton.me" },
    { id: "CUST040", name: "Hannah Evans", email: "hannah.evans@gmail.com" },
];


export const SEED_PRODUCTS: SeedProduct[] = [
    { id: "IPH14", name: "Apple iPhone 14" },
    { id: "IPH14P", name: "Apple iPhone 14 Pro" },
    { id: "IPH15", name: "Apple iPhone 15" },
    { id: "IPH15P", name: "Apple iPhone 15 Pro" },
    { id: "IPAD10", name: "Apple iPad 10th Gen" },
    { id: "IPADAIR", name: "Apple iPad Air M2" },
    { id: "MBAIR", name: "Apple MacBook Air M3" },
    { id: "MBPRO", name: "Apple MacBook Pro 14" },
    { id: "AW9", name: "Apple Watch Series 9" },
    { id: "APP2", name: "Apple AirPods Pro 2" },
    { id: "SAM24", name: "Samsung Galaxy S24" },
    { id: "SAM24U", name: "Samsung Galaxy S24 Ultra" },
    { id: "SAMZ6", name: "Samsung Galaxy Z Fold 6" },
    { id: "SAMTAB", name: "Samsung Galaxy Tab S9" },
    { id: "SAMBU", name: "Samsung Galaxy Buds3 Pro" },
    { id: "PIX8", name: "Google Pixel 8" },
    { id: "PIX8P", name: "Google Pixel 8 Pro" },
    { id: "PIX9", name: "Google Pixel 9" },
    { id: "GPBUDS", name: "Google Pixel Buds Pro" },
    { id: "ONE12", name: "OnePlus 12" },
    { id: "ONE12R", name: "OnePlus 12R" },
    { id: "XIA14", name: "Xiaomi 14" },
    { id: "XIA14U", name: "Xiaomi 14 Ultra" },
    { id: "OPFIND", name: "Oppo Find X7 Ultra" },
    { id: "VIVX100", name: "Vivo X100 Pro" },
    { id: "NOTH2", name: "Nothing Phone (2)" },
    { id: "SONX5", name: "Sony Xperia 1 VI" },
    { id: "HONM6", name: "Honor Magic 6 Pro" },
    { id: "MOTOE", name: "Motorola Edge 50 Pro" },
    { id: "ASUSZ", name: "ASUS ROG Phone 8" },
    { id: "DELXPS", name: "Dell XPS 13" },
    { id: "HPENVY", name: "HP Envy x360" },
    { id: "LENYGA", name: "Lenovo Yoga Slim 7" },
    { id: "MSFSUR", name: "Microsoft Surface Pro 11" },
    { id: "LGGRAM", name: "LG Gram 16" },
    { id: "BOSEQC", name: "Bose QuietComfort Ultra" },
    { id: "SONWH", name: "Sony WH-1000XM5" },
    { id: "JBLFL", name: "JBL Flip 6 Speaker" },
    { id: "KINDLE", name: "Amazon Kindle Paperwhite" },
    { id: "ECHOD", name: "Amazon Echo Dot 5th Gen" },
];


export const SEED_INVENTORY: SeedInventoryItem[] = [
    { productId: "IPH14", quantity: 42 },
    { productId: "IPH14P", quantity: 28 },
    { productId: "IPH15", quantity: 55 },
    { productId: "IPH15P", quantity: 31 },
    { productId: "IPAD10", quantity: 36 },
    { productId: "IPADAIR", quantity: 22 },
    { productId: "MBAIR", quantity: 18 },
    { productId: "MBPRO", quantity: 14 },
    { productId: "AW9", quantity: 47 },
    { productId: "APP2", quantity: 63 },
    { productId: "SAM24", quantity: 39 },
    { productId: "SAM24U", quantity: 24 },
    { productId: "SAMZ6", quantity: 11 },
    { productId: "SAMTAB", quantity: 27 },
    { productId: "SAMBU", quantity: 44 },
    { productId: "PIX8", quantity: 33 },
    { productId: "PIX8P", quantity: 19 },
    { productId: "PIX9", quantity: 41 },
    { productId: "GPBUDS", quantity: 52 },
    { productId: "ONE12", quantity: 29 },
    { productId: "ONE12R", quantity: 37 },
    { productId: "XIA14", quantity: 26 },
    { productId: "XIA14U", quantity: 15 },
    { productId: "OPFIND", quantity: 12 },
    { productId: "VIVX100", quantity: 17 },
    { productId: "NOTH2", quantity: 34 },
    { productId: "SONX5", quantity: 9 },
    { productId: "HONM6", quantity: 21 },
    { productId: "MOTOE", quantity: 30 },
    { productId: "ASUSZ", quantity: 8 },
    { productId: "DELXPS", quantity: 16 },
    { productId: "HPENVY", quantity: 23 },
    { productId: "LENYGA", quantity: 20 },
    { productId: "MSFSUR", quantity: 13 },
    { productId: "LGGRAM", quantity: 10 },
    { productId: "BOSEQC", quantity: 48 },
    { productId: "SONWH", quantity: 56 },
    { productId: "JBLFL", quantity: 61 },
    { productId: "KINDLE", quantity: 72 },
    { productId: "ECHOD", quantity: 0 },
];
